import Navbar from "@/components/claim_list/Navbar";
import "../globals.css";
import StoreProvider from "../StoreProvider";


export const metadata = {
  title: "Task Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Navbar/>
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
